name: weather_app
description: A modern weather application with Firebase integration and beautiful UI.
version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.0
  cloud_firestore: ^4.3.0
  http: ^0.13.5
  geolocator: ^9.0.2
  google_fonts: ^4.0.3
  fl_chart: ^0.55.2
  flutter_spinkit: ^5.1.0
  json_annotation: ^4.8.1
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
