// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXMoe9pdHY1rJsk-Ca1pNPcWf-BRb8DYM',
    appId: '1:438118722885:web:c8bea7814c499aa30f222c',
    messagingSenderId: '438118722885',
    projectId: 'weather-app-96',
    authDomain: 'weather-app-96.firebaseapp.com',
    storageBucket: 'weather-app-96.firebasestorage.app',
    measurementId: 'G-FQW9BDY02W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwMPGfhKSpauQImQozJJ1RYjru3p2wX34',
    appId: '1:438118722885:android:36c6ee6982b558240f222c',
    messagingSenderId: '438118722885',
    projectId: 'weather-app-96',
    storageBucket: 'weather-app-96.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9JXzAGpTzED0Q1_4k8whsKthYLAaZ-Fo',
    appId: '1:438118722885:ios:f6e052ec357231540f222c',
    messagingSenderId: '438118722885',
    projectId: 'weather-app-96',
    storageBucket: 'weather-app-96.firebasestorage.app',
    iosClientId: '438118722885-vukmjs29j822grtj2h2h5fhtmtabahqa.apps.googleusercontent.com',
    iosBundleId: 'com.example.weatherApp96',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9JXzAGpTzED0Q1_4k8whsKthYLAaZ-Fo',
    appId: '1:438118722885:ios:f6e052ec357231540f222c',
    messagingSenderId: '438118722885',
    projectId: 'weather-app-96',
    storageBucket: 'weather-app-96.firebasestorage.app',
    iosClientId: '438118722885-vukmjs29j822grtj2h2h5fhtmtabahqa.apps.googleusercontent.com',
    iosBundleId: 'com.example.weatherApp96',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXMoe9pdHY1rJsk-Ca1pNPcWf-BRb8DYM',
    appId: '1:438118722885:web:f0570abfd5c2cc500f222c',
    messagingSenderId: '438118722885',
    projectId: 'weather-app-96',
    authDomain: 'weather-app-96.firebaseapp.com',
    storageBucket: 'weather-app-96.firebasestorage.app',
    measurementId: 'G-JF0EYHBE1J',
  );
}
